# SwiftLint configuration for Cleansi

# Paths to include
included:
  - Cleansi

# Paths to exclude
excluded:
  - build
  - .build
  - Pods
  - Carthage

# Enabled rules
opt_in_rules:
  - closure_spacing
  - empty_count
  - explicit_init
  - fatal_error_message
  - first_where
  - force_unwrapping
  - implicitly_unwrapped_optional
  - joined_default_parameter
  - overridden_super_call
  - redundant_nil_coalescing
  - sorted_imports
  - toggle_bool
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - vertical_whitespace_closing_braces

# Disabled rules
disabled_rules:
  - line_length  # We use 120 char ruler but don't enforce
  - trailing_whitespace  # Can be noisy
  - todo  # Allow TODO comments

# Rule configurations
indentation:
  severity: warning
  indentation_width: 2
  include_comments: false
  include_compiler_directives: false
  include_multiline_strings: false
  indent_switch_case: true
  indent_switch_case_from_colon: false

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 50
    error: 60
  excluded:
    - id
    - i
    - j
    - x
    - y

type_name:
  min_length:
    warning: 3
    error: 2
  max_length:
    warning: 50
    error: 60

function_body_length:
  warning: 50
  error: 100

file_length:
  warning: 400
  error: 1000

type_body_length:
  warning: 300
  error: 500

cyclomatic_complexity:
  warning: 15
  error: 25

nesting:
  type_level:
    warning: 2
  function_level:
    warning: 3

# Reporter type (xcode, json, csv, checkstyle, codeclimate, junit, html, emoji, sonarqube, markdown, github-actions-logging)
reporter: "xcode"
